
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include /config/PaddiSense/Shell/shell_command.yaml

homeassistant:
  packages: !include_dir_named /config/PaddiSense/YAMLS




##########################
# This setting will kepp all data in the database for 1 year then be deleted
recorder:
  purge_keep_days: 365
  auto_purge: true
  commit_interval: 30
############################

#################################################
# Steps to sync with Github
#     >> git add PaddiSense
#     >> git commit -m "Add PaddiSense folder"
#     >> git push
